### PR TITLE
Expand language.lua data to include Roblox v514 & v517 changes.

### PR DESCRIPTION
**Pull request by AyhanDalkiran**
This pull request implements the following changes to `language.lua`:
```diff
+Font
+Font.new
+Font.fromEnum
+table.clone
+task.cancel
-TextChatMessageProperties
-TextChatMessageProperties.new
```

Will keep this as a draft until release notes come out.

### CODE REVIEW

**Comment by AyhanDalkiran** [comment]
It is ready for merging now.

**Comment by boatbomber** [comment]
I'm a little iffy on adding things before they're properly released, like how we've now added and removed `TextChatMessageProperties` since it was an internal WIP and didn't make it. Perhaps we should hold out?

**Comment by AyhanDalkiran** [comment]
> I'm a little iffy on adding things before they're properly released, like how we've now added and removed `TextChatMessageProperties` since it was an internal WIP and didn't make it. Perhaps we should hold out?

Maybe. We could add the built-in globals that are present or mentioned in the release notes like `task.cancel` and merge the unconfirmed ones in a later pull request when they are ready for public use.

**Comment by boatbomber** [comment]
`task.cancel` isn't enabled yet though, so I'd wait on that too.

**Comment by AyhanDalkiran** [comment]
@boatbomber So uh, question. Should I also include v517 changes in this pull request too or should I just create a separate pull request for it?

**Comment by boatbomber** [comment]
You can add it to this one to keep things simpler. These changes are entirely non-breaking so strict careful versioning is more a hinderance to us than a benefit.

**Comment by AyhanDalkiran** [comment]
Alright then.

**Pull request merged**
