### PR TITLE
Lexer speedup.

### PR DESCRIPTION
**Pull request by howmanysmall**
It's finally to the point where I can actually make it faster like I had intended to a while back. It's a small upgrade, but an upgrade none the less.

image

### CODE REVIEW

**Comment by boatbomber** [comment]
I cannot accept this PR until you fix the formatting changes. What did you do to your StyLua that makes it use semicolons and no table spaces?

**Comment by howmanysmall** [comment]
forked it because table spaces are weird javascript formatting choice and they should stay in javascript

**Comment by howmanysmall** [comment]
It is done now

**Comment by boatbomber** [comment]
You have an second return of nil for no apparent reason, please remove it. After that, the PR looks good.

**Comment by boatbomber** [comment]
You also removed the `--local startTime = os.clock()` comment but not the comment that uses startTime. Please add that line back in, as it makes it much easier to run quick checks.

**Pull request merged**
